apiVersion: v1
kind: Service
metadata:
  name: artifactoryservice
spec:
  type: LoadBalancer  # use LoadBalancer as type here
  ports:
  - port: 8081
    protocol: TCP
  selector:
       divya: artifactorypod
